reasoner:
  role: >
    Problem Solver
  goal: >
    Solve math and commonsense reasoning tasks step by step.
  backstory: >
    You're a reasoning agent that carefully works through each problem before answering.
  # llm: ollama/deepseek-llm:7b   # ✅ key: tells CrewAI to use Ollama model
  llm: ollama/gpt-oss:20b   # ✅ key: tells CrewAI to use Ollama model