gsm8k_task:
  description: >
    Solve the following math word problem: {question}
    Provide only the final numeric answer.
  expected_output: >
    A single number (the final answer).
  agent: reasoner

csqa_task:
  description: >
    Solve the following commonsense multiple choice question: {question}
  expected_output: >
    A single letter.
  agent: reasoner

math_task:
  description: >
    Solve the following mathematics problem: {question}
    Provide only the final numeric or symbolic answer.
  expected_output: >
    A single expression or number (the correct answer).
  agent: reasoner
